### ISSUE TITLE
Delayed registration / allow unregistered use

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#45] opened 2017-02-17 15:07 UTC
What is the current behavior in this scenario:

1. User is not registered or signed in.
2. User adds a couple notes
3. User registers

Do the notes the user made offline get synced automatically? This should be the case.

**Comment by herbig** [comment] 2017-02-17 16:18
The app currently starts at the login/registration screen, so you can't write notes until you've logged into an account.

**Comment by mobitar** [comment] 2017-02-17 16:19
Hmm..that's no good. It's sort of SN's signature to get out of your way ;) How hard a change is this?

**Comment by herbig** [comment] 2017-02-17 16:24
It shouldn't be too difficult at all. Starting at the login screen is probably a temporary measure to get things going.

**Comment by deftelf** [comment] 2017-02-17 17:21
The sync would be disabled without a sync token... but I don't think this should be too much of an issue since everything is written to disk and synced later. The Sync later step would just be much further in the future when a token is finally found.
The biggest issue is how the UI would work. What happens if you log out in iOS? Does it delete all the data?

**Comment by mobitar** [comment] 2017-02-17 17:35
Yes when you log out it deletes all data (shows a confirmation before though). What do you mean about disabled without a sync token?

**Comment by deftelf** [comment] 2017-02-17 17:47
Sorry wrong term. Without a webtoken - ie authentication

**Comment by deftelf** [comment] 2017-04-24 22:01
Dupe of #90

**Closed by deftelf** 2017-04-24 22:01 UTC
Labels: enhancement, Normal priority
